### ISSUE TITLE
Can not use the library in strict mode.

### ISSUE THREAD

**Issue by duc01226** [zeeshanhyder/angular-right-click#4]
Can we create a new release for this fix ? I see that we fixed this, but we didn't create a new release.

**Comment by zeeshanhyder** [comment]
Please use the fix locally for now. I will update this with the next release. Thankyou for letting me know about the issue. :+1:

**Comment by zeeshanhyder** [comment]
Could you please let me know all the details? How are you facing the issue? Thanks. @duc01226

**Comment by duc01226** [comment]
Hi @zeeshanhyder . Thanks for your reply.
- In my application, I used "ng-strict-di". Reference : [https://docs.angularjs.org/api/ng/directive/ngApp](url)
- In ng-right-click.js, we have this part which is not allowed in strict mode : 
![image](https://cloud.githubusercontent.com/assets/9187471/22972508/83e60864-f3ac-11e6-998e-433b1732a4d5.png)
- We need to use explicit function annotation, like in your current source code, which is not included in a new release : 
![image](https://cloud.githubusercontent.com/assets/9187471/22972589/d5d112d6-f3ac-11e6-9c53-5d039b2e5bba.png)

**Comment by duc01226** [comment]
Hi @zeeshanhyder ,

Could you please check to create a new release to fix this issue ?

**Comment by zeeshanhyder** [comment]
@duc01226 Sure. I'll release new version in a while.

Thanks.

**Comment by zeeshanhyder** [comment]
Fixed by commit https://github.com/zeeshanhyder/angular-right-click/commit/2257a49164ca46bca46521b2332534820dbcd29d
